### ISSUE TITLE
Open ports within RTUN TUI

### ISSUE THREAD

**Issue by FredCarvalhoOliveira** [andycancado/rtun#1]
![image](https://github.com/andycancado/rtun/assets/8009517/3400debd-a51f-4456-859e-00505244ea20)

## Open ports within RTUN TUI

Currently RTUN can only open ports on initialization, it would be great if you could open and close ports within the TUI posted above.

Great tool btw, thanks for sharing this

**Comment by andycancado** [comment]
thnks for the feedback, the team will work on this ASAP.. xD

**Comment by andycancado** [comment]
Thanks for your feedback, is implemented on version 0.1.1

**Comment by andycancado** [comment]
thnks
